project_id = "jeurznrjcohqbevrzses"

[functions.team-management]
verify_jwt = true

[functions.send-invitation]
verify_jwt = false

[functions.openrouter-chat]
verify_jwt = true

[functions.openrouter-chat-stream]
verify_jwt = true

[functions.claude-chat-stream]
verify_jwt = true

[functions.gemini-chat-stream]
verify_jwt = true

[functions.deepseek-chat-stream]
verify_jwt = true

[functions.huggingface-image]
verify_jwt = false

[functions.web-search-advanced]
verify_jwt = true

[functions.image-proxy]
verify_jwt = false

[functions.dalle-image]
verify_jwt = false

[functions.openai-image-edit]
verify_jwt = false

[functions.openai-image-variations]
verify_jwt = false

[functions.veo2-video]
verify_jwt = false

[functions.veo3-video]
verify_jwt = false

[functions.kling-official-video]
verify_jwt = false

[functions.gemini-chat]
verify_jwt = true

[functions.deepseek-chat]
verify_jwt = true

[functions.claude-chat]
verify_jwt = true

[functions.codestral-chat]
verify_jwt = true

[functions.perplexity-chat]
verify_jwt = true

[functions.youtube-audio-extract]
verify_jwt = false

[functions.translate-text]
verify_jwt = false

[functions.generate-ebook]
verify_jwt = true